events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    server {
        listen 80;
        server_name witcher3-infrastructure.ru www.witcher3-infrastructure.ru;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        } 
        location / {
            root /.well-known/acme-challenge/
                root /var/www/certbot;
        }
    }

    server {
        listen 80;
        server_name grafana.witcher3-infrastructure.ru;
        location / {
            proxy_pass http://grafana:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location / {
            root /.well-known/acme-challenge/
                root /var/www/certbot;
        }
    }

    server {
        listen 80;
        server_name prometheus.witcher3-infrastructure.ru;
        location / {
            proxy_pass http://prometheus:9090;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location / {
            root /.well-known/acme-challenge/
                root /var/www/certbot;
        }
    }

    server {
        listen 80;
        server_name alertmanager.witcher3-infrastructure.ru;
        location / {
            proxy_pass http://alertmanager:9093;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location / {
            root /.well-known/acme-challenge/
                root /var/www/certbot;
        }
    }
}