events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    # witcher 3 site
    server {
        listen 80;
        server_name witcher3-infrastructure.ru www.witcher3-infrastructure.ru;
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name witcher3-infrastructure.ru www.witcher3-infrastructure.ru;
        # Пути к сертификатам, которые мы пробросили из Certbot
        ssl_certificate /etc/letsencrypt/live/witcher3-infrastructure.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/witcher3-infrastructure.ru/privkey.pem;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }

    # grafana
    server {
        listen 80;
        server_name grafana.witcher3-infrastructure.ru;
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name grafana.witcher3-infrastructure.ru;
        ssl_certificate /etc/letsencrypt/live/witcher3-infrastructure.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/witcher3-infrastructure.ru/privkey.pem;
        location / {
            proxy_pass http://grafana:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # prometheus
    server {
        listen 80;
        server_name prometheus.witcher3-infrastructure.ru;
        location / {
            return 301 https://$host$request_uri;
        }
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
    }

    server {
        listen 443 ssl;
        server_name prometheus.witcher3-infrastructure.ru;
        ssl_certificate /etc/letsencrypt/live/witcher3-infrastructure.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/witcher3-infrastructure.ru/privkey.pem;
        location / {
            proxy_pass http://prometheus:9090;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # alertmanager
    server {
        listen 80;
        server_name alertmanager.witcher3-infrastructure.ru;
        location / {
            return 301 https://$host$request_uri;
        }
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

    }

    server {
        listen 443 ssl;
        server_name alertmanager.witcher3-infrastructure.ru;
        ssl_certificate /etc/letsencrypt/live/witcher3-infrastructure.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/witcher3-infrastructure.ru/privkey.pem;
        location / {
            proxy_pass http://alertmanager:9093;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}