route:
  receiver: 'tg_bot'
  repeat_interval: 15m

receivers:
  - name: 'tg_bot'
    telegram_configs:
      - bot_token: '<YOUR_TELEGRAM_BOT_TOKEN_HERE>'
        chat_id: <YOUR_CHAT_ID_HERE>
        http_config: 
          proxy_url: 'http://твой_логин:твой_пароль@IP_ГЕРМАНСКОЙ_VPS:2080'
        parse_mode: 'HTML'
        message: |
          <b>[УВЕДОМЛЕНИЕ]</b>
          {{ if eq .Status "firing" }}🚨 <b>СБОЙ:</b>{{ else }}✅ <b>ВОССТАНОВЛЕНИЕ:</b>{{ end }}
          <b>Алерт:</b> {{ .CommonLabels.alertname }}
          <b>Важность:</b> {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          <b>Описание:</b> {{ .Annotations.description }}
          <b>Время старта:</b> {{ .StartsAt.Local.Format "2006-01-02 15:04:05" }}
          {{ end }}