groups:
  - name: container_alerts
    rules: 
      - alert: NginxContainerDown
        expr: (time() - container_last_seen{name="nginx"} > 60) or absent(container_last_seen{name="nginx"})
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Контейнер Nginx недоступен!"
          description: "cAdvisor сообщает, что Nginx остановлен или не отвечает."