groups:
  - name: container_alerts
    rules: 
      - alert: NginxContainerDown
        expr: up{job="nginx"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Контейнер Nginx недоступен!"
          description: "Метрика up{job='nginx'} равна 0 уже более 1 минуты. Контейнер на хосте {{ $labels.instance }} мог остановиться."